name: Deploy
run-name: ${{ inputs.id }}

on:
  workflow_dispatch:
    inputs:
      id:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      app_name:
        required: true
        type: string
      commit_hash:
        required: true
        type: string
      environment:
        required: true
        type: string
      deployment_type:
        required: true
        type: string

permissions:
  contents: read
  packages: read # for npm packages installation

jobs:
  # Dummy job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Mock Deployment with Random Wait
        run: |
          echo "Starting deployment of ${{ inputs.repo_name }}/${{ inputs.app_name }} to ${{ inputs.environment }}"
          echo "Commit: ${{ inputs.commit_hash }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Deployment Type: ${{ inputs.deployment_type }}"
          
          # Print the workflow template that would be used
          if [ "${{ inputs.deployment_type }}" = "frontend" ]; then
            echo "Uses: tpai/workflows/.github/workflows/deploy-frontend.yml@main"
          else
            echo "Uses: tpai/workflows/.github/workflows/deploy-backend.yml@main"
          fi

          # Generate random wait time between 10-30s
          WAIT_TIME=$(( ( RANDOM % 3 ) + 1 ))
          echo "Simulating deployment for $WAIT_TIME seconds..."
          sleep $(( WAIT_TIME * 10 ))
          
          echo "Deployment to ${{ inputs.environment }} completed successfully!"
